version: '3.8'

services:
  fighter-service:
    build:
      context: .
      network: host
    restart: always
    container_name: web-api
    ports:
      - 8080:8080
    networks:
      service-network:
    depends_on:
      - mongodb

  mongodb:
    container_name: mongodb
    image: mongo
    restart: always
    volumes:
      - data-db:/data/db
    networks:
      service-network:
    ports:
      - 27017:27017
volumes:
  data-db:
networks:
  service-network:
